# Generated by Django 5.0.3 on 2025-01-16 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uservisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
