# Generated by Django 5.0.3 on 2025-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uservisit_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
