# Generated by Django 5.0.3 on 2025-03-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
