# Generated by Django 5.0.3 on 2025-03-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_contact_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
