# Generated by Django 5.0.3 on 2025-08-24 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_contact_full_name_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='read_time',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated read time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
