# Generated by Django 5.0.3 on 2025-08-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
