# Generated by Django 5.0.3 on 2025-08-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_skill_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='publish',
            new_name='published',
        ),
    ]
