# Generated by Django 5.0.3 on 2025-09-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_publish_skill_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance'),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
