# Generated by Django 5.0.3 on 2025-09-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issued_by',
            new_name='issuer',
        ),
    ]
