# Generated by Django 5.0.3 on 2025-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
            preserve_default=False,
        ),
    ]
