# Generated by Django 5.0.3 on 2026-06-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog/default.png', null=True, upload_to='blog'),
        ),
    ]
